version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - '5433:5432'
    volumes:
      - datadb:/var/lib/postgresql/data
volumes:
  datadb:
    driver: local
